import React, { useEffect, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import axios from "axios";
import { Brand, StatusBadge } from "../components/Common";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

export default function PropertyShareReport() {
  const { id } = useParams();
  const [params] = useSearchParams();
  const token = params.get("t");
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    axios.get(`${API}/public/property-report/${id}?t=${encodeURIComponent(token || "")}`)
      .then(({ data }) => setData(data))
      .catch((e) => setError(e?.response?.data?.detail || "Could not load report"));
  }, [id, token]);

  if (error) return <Wrap><div className="p-10 text-center text-slate-600" data-testid="share-error">{error}</div></Wrap>;
  if (!data) return <Wrap><div className="p-10 text-center text-slate-500">Loading report…</div></Wrap>;

  const p = data.property;
  const compliant = data.compliance.filter((c) => c.status === "compliant").length;
  return (
    <Wrap>
      <div className="p-6 md:p-10 max-w-5xl mx-auto" data-testid="share-report">
        <div className="label-eyebrow">Property Health Report · Read-only</div>
        <h1 className="font-display text-3xl md:text-4xl font-bold tracking-tight mt-2">{p.address}</h1>
        <div className="text-slate-600">{p.suburb}, {p.city} · {p.bedrooms} bed · {p.bathrooms} bath</div>
        <div className="text-xs text-slate-500 mt-1 font-mono">Generated {new Date(data.generated_at).toLocaleString()}</div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-8">
          <Tile label="Risk score" value={p.risk_score} accent={p.risk_score > 50} />
          <Tile label="Compliance" value={`${compliant}/${data.compliance.length}`} />
          <Tile label="Open tickets" value={data.tickets.filter(t => !["completed","closed"].includes(t.status)).length} />
          <Tile label="Inspections" value={data.inspections.length} />
        </div>

        <h2 className="font-display text-xl font-bold mt-10 mb-3">Healthy Homes compliance</h2>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          {data.compliance.map((c) => (
            <div key={c.id} className="bg-white border border-slate-200 p-4" data-testid={`share-compliance-${c.area}`}>
              <div className="label-eyebrow">{c.area.replace("_"," ")}</div>
              <div className="mt-2"><StatusBadge status={c.status} /></div>
            </div>
          ))}
        </div>

        <h2 className="font-display text-xl font-bold mt-10 mb-3">Recent tickets</h2>
        {data.tickets.length === 0 ? <div className="text-sm text-slate-500">No tickets.</div> : (
          <div className="bg-white border border-slate-200">
            <table className="w-full text-sm">
              <thead className="bg-slate-50"><tr className="text-left"><th className="px-4 py-2 label-eyebrow">Title</th><th className="px-4 py-2 label-eyebrow">Urgency</th><th className="px-4 py-2 label-eyebrow">Status</th><th className="px-4 py-2 label-eyebrow text-right">Date</th></tr></thead>
              <tbody>{data.tickets.map((t) => (
                <tr key={t.id} className="border-t border-slate-100">
                  <td className="px-4 py-2"><div className="font-semibold">{t.title}</div>{t.healthy_homes && <span className="text-[10px] font-bold uppercase tracking-wider bg-[#004B87] text-white px-1.5 py-0.5">Healthy Homes</span>}</td>
                  <td className="px-4 py-2"><StatusBadge status={t.urgency} /></td>
                  <td className="px-4 py-2"><StatusBadge status={t.status} /></td>
                  <td className="px-4 py-2 text-right font-mono text-xs text-slate-500">{new Date(t.created_at).toLocaleDateString()}</td>
                </tr>
              ))}</tbody>
            </table>
          </div>
        )}

        <h2 className="font-display text-xl font-bold mt-10 mb-3">Inspections</h2>
        {data.inspections.length === 0 ? <div className="text-sm text-slate-500">No inspections yet.</div> : (
          <div className="space-y-3">{data.inspections.map((i) => (
            <div key={i.id} className="bg-white border border-slate-200 p-4">
              <div className="flex items-center justify-between mb-1"><StatusBadge status={i.status === "in_progress" ? "in_progress" : i.status === "completed" ? "completed" : "open"}>{i.status.replace("_"," ")}</StatusBadge><div className="text-xs font-mono text-slate-500">{new Date(i.created_at).toLocaleDateString()} · {i.room_count} rooms</div></div>
              {i.summary && <p className="text-sm text-slate-700 mt-2">{i.summary}</p>}
            </div>
          ))}</div>
        )}

        <div className="mt-12 text-xs text-slate-500 text-center">This report was generated by Dwelloro. Read-only — no login required.</div>
      </div>
    </Wrap>
  );
}

function Wrap({ children }) {
  return (
    <div className="min-h-screen bg-[#F8FAFC]">
      <header className="border-b border-slate-200 bg-white"><div className="max-w-5xl mx-auto px-6 h-14 flex items-center"><Brand /></div></header>
      {children}
    </div>
  );
}

function Tile({ label, value, accent = false }) {
  return (
    <div className={`bg-white border border-slate-200 p-4 ${accent ? "border-l-4 border-l-[#FF5722]" : ""}`}>
      <div className="label-eyebrow">{label}</div>
      <div className="font-display text-3xl font-bold mt-1">{value}</div>
    </div>
  );
}
